name: Build and Push n8n FFmpeg Docker Image

on:
  push:
    branches:
      - main # Or whatever branch your Dockerfile is on
    paths:
      - 'Dockerfile' # Trigger only when Dockerfile changes
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

env:
  DOCKER_IMAGE_NAME: romansauter/n8n-ffmpeg-custom # Replace with your image name
  DOCKER_IMAGE_TAG: latest

jobs:
  build_and_push:
    runs-on: ubuntu-latest # Use a fresh Ubuntu runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Stored as a GitHub Secret
        password: ${{ secrets.DOCKER_PASSWORD }} # Stored as a GitHub Secret

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: . # Path to the build context (where your Dockerfile is)
        file: ./Dockerfile # Path to your Dockerfile
        push: true # Push the image to the registry
        tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
        platforms: linux/amd64 # Specify platform if needed (e.g., for multi-arch builds)

    - name: Verify Image Tag
      run: echo "Docker Image Pushed: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}"
